### ISSUE TITLE
Uncaught TypeError: $(...).typed is not a function

### ISSUE THREAD

**Issue by pramitbiswas** [mattboldt/typed.js#425]
### Description

Working fine with
`https://cdnjs.cloudflare.com/ajax/libs/typed.js/1.1.7/typed.min.js`
[Fiddle](https://jsfiddle.net/92je0zch/2/)

Not working with (any release from 2.0.0)
`https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.9/typed.min.js`
[Fiddle](https://jsfiddle.net/92je0zch/3/)

Error:
Uncaught TypeError: $(...).typed is not a function
    at typeWords

**Comment by Dob6458** [comment]
Try to use CDN Jsdelivr to get versions of the repositories.

https://cdn.jsdelivr.net

**Comment by Dob6458** [comment]
For example:
https://cdn.jsdelivr.net/gh/mattboldt/lib/typed.js

**Comment by Dob6458** [comment]
What do you think ?

**Comment by pramitbiswas** [comment]
> https://cdn.jsdelivr.net/gh/mattboldt/typed.js/lib/typed.js

nope, does not work. You can use linked Fiddle.

**Comment by Dob6458** [comment]
Do you use jQuery? maybe is that.

**Comment by Dob6458** [comment]
No, wait...
Don't use the `$` symbols, it's `new Typed("#typed", options)`

**Comment by dimative** [comment]
Same problem. I want to display multiple typed texts on one page. 
Old way works fine.  ```$('.element').type({options})```
New way ```new Typed("#typed", {options})```` will work on single typed element.

If i want to display multiple widgets usign typed js, how can i do it with new way?

**Comment by pramitbiswas** [comment]
Alright.
For `https://cdn.jsdelivr.net/npm/typed.js@2.0.9` or `https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.9/typed.min.js`, the changes needed are as follow:

`$(".typedC").typed({` to `new Typed(".typedC", {`

Updated working [Fiddle](https://jsfiddle.net/usa0pkmg/) compared to not working [Fiddle](https://jsfiddle.net/92je0zch/3/), the changes are in line 6, of javascript.

Thanks.

**Comment by Dob6458** [comment]
@dimative, use the arrays for multiple widgets:
```js
var typings = [
  new Typed(".span"),
  new Typed("#div")
]
```

**Comment by 1703011** [comment]
hello @Dob6458 . I had the same issue. The problem was solved by changing `$(".typedC").typed({` to `new Typed('.element', {options})` . Do you mind explain why this solves the problem? Thanks.
